### ISSUE TITLE
eta0 // Adam's epoch service fails for 252

### ISSUE THREAD

**Issue by 7-of-9** [DamjanOstrelic/cardano-leader-logs#4]
eg.: https://epoch-api.crypto2099.io:2096/epoch/252
==> {"message":"Could not find the epoch you were looking for."}

@DamjanOstrelic do you know if the instructions in the readme re. `Shelley/Protocol.hs` still stand, now that we're on Mary era? Also, is there not by now a friendlier/easier way to get to this eta0 value?

Thanks in advance! 
D.

**Comment by 7-of-9** [comment]
https://github.com/papacarp/pooltool.io/commit/7d8d37627ac1c4e4ea0f92d002b658ccadc18770

**Comment by dostrelith678** [comment]
`cardano-cli query protocol-state --mainnet --mary-era | jq -r .csTickn.ticknStateEpochNonce.contents`
