### ISSUE TITLE
errors

### ISSUE THREAD

**Issue by nilaysaha** [DamjanOstrelic/cardano-leader-logs#8]
I had to change the following two params:

-const params                  = JSON.parse(fs.readFileSync(process.argv[2]))
-const epochNonce              = process.argv[3]

in

cardanoLeaderLogs.js to make it work. (just the params were shifted )

Run env: 1.27.0 and i just cloned the repo today.

**Comment by dostrelith678** [comment]
Can you first confirm that you are on cardano-node version 1.27.0, and that you have the latest changes from this repo's `main` branch?

What command did you use to start the script?

It looks like you didn't specify the epoch nonce.

**Comment by nilaysaha** [comment]
@DamjanOstrelic : How could i open a Pull request. I am not permitted to open and push a branch.  Have to propose some changes to make the tool more consistent and easier to use.

fatal: unable to access 'https://github.com/DamjanOstrelic/cardano-leader-logs.git/': The requested URL returned error: 403

**Comment by dostrelith678** [comment]
I think you have to fork the repo, make the branch on your own repo, and then compare across forks.
